using System.Text;
using System.Xml.Linq;
using McdcTool.Core.Models;
using McdcTool.Core.Parsing;

namespace McdcTool.Core.CodeGen;

public class TestProjectGenerator
{
    private readonly XUnitTestGenerator _testGenerator = new();

    // Built-in test package names to avoid duplicating
    private static readonly HashSet<string> BuiltInPackages = new(StringComparer.OrdinalIgnoreCase)
    {
        "Microsoft.NET.Test.Sdk", "xunit", "xunit.runner.visualstudio", "coverlet.collector"
    };

    /// <summary>
    /// Generates a self-contained xUnit test project directory containing:
    /// - McdcTests.csproj  (runnable with dotnet test)
    /// - Generated *_McdcTests.cs test files
    /// - HOW_TO_RUN.txt   with usage instructions
    /// </summary>
    public void GenerateProject(
        List<string> sourceFiles,
        List<(DecisionInfo Decision, McdcResult Result)> analysisItems,
        string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        // Write generated test files
        foreach (var (decision, result) in analysisItems)
        {
            var testCode = _testGenerator.Generate(decision, result);
            var fileName = $"{Path.GetFileNameWithoutExtension(decision.FilePath)}_Line{decision.LineNumber}_McdcTests.cs";
            File.WriteAllText(Path.Combine(outputDir, fileName), testCode);
        }

        // Write .csproj
        var csprojContent = BuildCsproj(sourceFiles, outputDir);
        File.WriteAllText(Path.Combine(outputDir, "McdcTests.csproj"), csprojContent);

        // Write HOW_TO_RUN.txt
        File.WriteAllText(Path.Combine(outputDir, "HOW_TO_RUN.txt"), BuildReadme(outputDir));
    }

    private string BuildCsproj(List<string> sourceFiles, string outputDir)
    {
        var compileItems = new StringBuilder();
        bool needsWinForms = false;
        bool needsWpf = false;
        var extraPackages = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var src in sourceFiles.Distinct())
        {
            // Use relative path from the output directory to the source file
            string relativePath;
            try
            {
                relativePath = Path.GetRelativePath(outputDir, src).Replace('\\', '/');
            }
            catch
            {
                relativePath = src.Replace('\\', '/');
            }
            compileItems.AppendLine($"    <Compile Include=\"{relativePath}\" />");

            // Scan source file content for framework usage
            try
            {
                var content = File.ReadAllText(src);
                if (content.Contains("using System.Windows.Forms"))
                    needsWinForms = true;
                if (content.Contains("using System.Windows.Media") ||
                    content.Contains("using System.Windows.Controls") ||
                    content.Contains("using System.Windows.Markup"))
                    needsWpf = true;
            }
            catch { /* file may not be readable on this machine */ }
        }

        // Try to find and parse source project .csproj files for PackageReference items
        ExtractSourceProjectReferences(sourceFiles, extraPackages);

        // Build extra property lines
        var extraProps = new StringBuilder();
        if (needsWinForms)
            extraProps.AppendLine("    <UseWindowsForms>true</UseWindowsForms>");
        if (needsWpf)
            extraProps.AppendLine("    <UseWPF>true</UseWPF>");

        // Build extra package reference lines
        var extraPackageItems = new StringBuilder();
        foreach (var (name, version) in extraPackages)
        {
            if (BuiltInPackages.Contains(name)) continue;
            extraPackageItems.AppendLine($"    <PackageReference Include=\"{name}\" Version=\"{version}\" />");
        }

        var extraPackageSection = extraPackageItems.Length > 0
            ? $@"
  <!-- Package references from source project -->
  <ItemGroup>
{extraPackageItems}  </ItemGroup>
"
            : "";

        var targetFramework = (needsWinForms || needsWpf) ? "net10.0-windows" : "net10.0";

        return $@"<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>{targetFramework}</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateProgramFile>false</GenerateProgramFile>
{extraProps}    <!-- Generated by MC/DC Testing Tool -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=""Microsoft.NET.Test.Sdk"" Version=""17.8.0"" />
    <PackageReference Include=""xunit"" Version=""2.5.3"" />
    <PackageReference Include=""xunit.runner.visualstudio"" Version=""2.5.3"">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include=""coverlet.collector"" Version=""6.0.0"">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
{extraPackageSection}
  <!-- Analyzed source files - add any missing dependencies as needed -->
  <ItemGroup>
{compileItems}  </ItemGroup>

</Project>
";
    }

    /// <summary>
    /// Walks up from each source file's directory to find .csproj files,
    /// then extracts their PackageReference items.
    /// </summary>
    public static void ExtractSourceProjectReferences(
        List<string> sourceFiles,
        Dictionary<string, string> packageReferences)
    {
        var processedProjects = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var src in sourceFiles.Distinct())
        {
            var csprojPath = FindCsprojForFile(src);
            if (csprojPath == null || !processedProjects.Add(csprojPath))
                continue;

            try
            {
                var doc = XDocument.Load(csprojPath);
                foreach (var pkgRef in doc.Descendants()
                    .Where(e => e.Name.LocalName == "PackageReference"))
                {
                    var name = pkgRef.Attribute("Include")?.Value;
                    var version = pkgRef.Attribute("Version")?.Value
                                  ?? pkgRef.Elements().FirstOrDefault(e => e.Name.LocalName == "Version")?.Value
                                  ?? "*";
                    if (!string.IsNullOrEmpty(name) && !packageReferences.ContainsKey(name))
                        packageReferences[name] = version;
                }
            }
            catch { /* skip unparseable projects */ }
        }
    }

    /// <summary>
    /// Walks up directory tree from a source file to find the nearest .csproj.
    /// </summary>
    public static string? FindCsprojForFile(string sourceFilePath)
    {
        try
        {
            var dir = Path.GetDirectoryName(Path.GetFullPath(sourceFilePath));
            while (dir != null)
            {
                var csprojFiles = Directory.GetFiles(dir, "*.csproj");
                if (csprojFiles.Length > 0)
                    return csprojFiles[0];

                var parent = Directory.GetParent(dir);
                if (parent == null) break;
                dir = parent.FullName;
            }
        }
        catch { /* ignore filesystem errors */ }
        return null;
    }

    private static string BuildReadme(string outputDir)
    {
        return $"""
MC/DC Generated Test Project
==============================
Generated: {DateTime.Now:yyyy-MM-dd HH:mm}
Output directory: {outputDir}

PREREQUISITES
-------------
- .NET 10.0 SDK or later

BEFORE RUNNING
--------------
The generated test files contain TODO placeholders in each test method body.
You need to:
1. Replace the TODO comments with actual calls to the method/code under test.
2. Ensure any dependencies of the source files are included in McdcTests.csproj
   (add <PackageReference> or <ProjectReference> items as needed).

HOW TO RUN TESTS
----------------
  cd "{outputDir}"
  dotnet restore
  dotnet test

HOW TO COLLECT CODE COVERAGE
------------------------------
  dotnet test --collect:"XPlat Code Coverage"

  Coverage results (Cobertura XML) are written to:
    TestResults/<guid>/coverage.cobertura.xml

  To generate an HTML report, install ReportGenerator:
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"CoverageReport" -reporttypes:Html
    open CoverageReport/index.html

NOTE ON STATEMENT/DECISION COVERAGE SHOWN IN THE UI
-----------------------------------------------------
The percentages shown in the MC/DC Tool web UI are *static estimates* based on
which methods contain analyzed boolean decisions. The true runtime coverage is
measured by coverlet when you run the tests above.
""";
    }
}
