using McdcTool.Core.Models;
using McdcTool.Core.Parsing;

namespace McdcTool.Core.CodeGen;

public class TestProjectGenerator
{
    private readonly XUnitTestGenerator _testGenerator = new();

    /// <summary>
    /// Generates a self-contained xUnit test project directory containing:
    /// - McdcTests.csproj  (runnable with dotnet test)
    /// - Generated *_McdcTests.cs test files
    /// - HOW_TO_RUN.txt   with usage instructions
    /// </summary>
    public void GenerateProject(
        List<string> sourceFiles,
        List<(DecisionInfo Decision, McdcResult Result)> analysisItems,
        string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        // Write generated test files
        foreach (var (decision, result) in analysisItems)
        {
            var testCode = _testGenerator.Generate(decision, result);
            var fileName = $"{Path.GetFileNameWithoutExtension(decision.FilePath)}_Line{decision.LineNumber}_McdcTests.cs";
            File.WriteAllText(Path.Combine(outputDir, fileName), testCode);
        }

        // Write .csproj
        var csprojContent = BuildCsproj(sourceFiles, outputDir);
        File.WriteAllText(Path.Combine(outputDir, "McdcTests.csproj"), csprojContent);

        // Write HOW_TO_RUN.txt
        File.WriteAllText(Path.Combine(outputDir, "HOW_TO_RUN.txt"), BuildReadme(outputDir));
    }

    private string BuildCsproj(List<string> sourceFiles, string outputDir)
    {
        var compileItems = new System.Text.StringBuilder();
        foreach (var src in sourceFiles.Distinct())
        {
            // Use relative path from the output directory to the source file
            string relativePath;
            try
            {
                relativePath = Path.GetRelativePath(outputDir, src).Replace('\\', '/');
            }
            catch
            {
                relativePath = src.Replace('\\', '/');
            }
            compileItems.AppendLine($"    <Compile Include=\"{relativePath}\" />");
        }

        return $@"<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject>
    <!-- Generated by MC/DC Testing Tool -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=""Microsoft.NET.Test.Sdk"" Version=""17.8.0"" />
    <PackageReference Include=""xunit"" Version=""2.5.3"" />
    <PackageReference Include=""xunit.runner.visualstudio"" Version=""2.5.3"">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include=""coverlet.collector"" Version=""6.0.0"">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Analyzed source files - add any missing dependencies as needed -->
  <ItemGroup>
{compileItems}  </ItemGroup>

</Project>
";
    }

    private static string BuildReadme(string outputDir)
    {
        return $"""
MC/DC Generated Test Project
==============================
Generated: {DateTime.Now:yyyy-MM-dd HH:mm}
Output directory: {outputDir}

PREREQUISITES
-------------
- .NET 8.0 SDK or later

BEFORE RUNNING
--------------
The generated test files contain TODO placeholders in each test method body.
You need to:
1. Replace the TODO comments with actual calls to the method/code under test.
2. Ensure any dependencies of the source files are included in McdcTests.csproj
   (add <PackageReference> or <ProjectReference> items as needed).

HOW TO RUN TESTS
----------------
  cd "{outputDir}"
  dotnet restore
  dotnet test

HOW TO COLLECT CODE COVERAGE
------------------------------
  dotnet test --collect:"XPlat Code Coverage"

  Coverage results (Cobertura XML) are written to:
    TestResults/<guid>/coverage.cobertura.xml

  To generate an HTML report, install ReportGenerator:
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:"CoverageReport" -reporttypes:Html
    open CoverageReport/index.html

NOTE ON STATEMENT/DECISION COVERAGE SHOWN IN THE UI
-----------------------------------------------------
The percentages shown in the MC/DC Tool web UI are *static estimates* based on
which methods contain analyzed boolean decisions. The true runtime coverage is
measured by coverlet when you run the tests above.
""";
    }
}
